trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - Phonebook.MockBackend/**

jobs:
  - job: build
    displayName: build docker image
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: |
          docker build .
        workingDirectory: 'Phonebook.MockBackend/'
