# https://github.com/cds-snc/github-actions/tree/master/node-license-checker
name: Check for Licences

on: [push]

jobs:
  check-licenses:
    runs-on: ubuntu-18.04
    steps:
    - name: Check for Licenses
      uses: docker://cdssnc/node-license-checker-github-action
      with:
        args: --direct --start ./Phonebook.Frontend --onlyAllow "MIT"
 
